services:
  
  airflow-webserver:
      image: apache/airflow:2.8.3
      container_name: airflow-webserver
      restart: always
      depends_on:
        - postgres
      environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor  # Use LocalExecutor instead of CeleryExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:password@postgres/airflow
        - AIRFLOW__CORE__FERNET_KEY=YOUR_FERNET_KEY  # Generate a Fernet key and replace it here
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
      volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./plugins:/opt/airflow/plugins
      ports:
        - "8080:8080"
    
  airflow-scheduler:
      image: apache/airflow:2.8.3
      container_name: airflow-scheduler
      restart: always
      depends_on:
        - postgres
      environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor  # Use LocalExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:password@postgres/airflow
      volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./plugins:/opt/airflow/plugins
    
  airflow-init:
      image: apache/airflow:2.8.3
      container_name: airflow-init
      environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor  # Use LocalExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:password@postgres/airflow
        - AIRFLOW__CORE__FERNET_KEY=8zyd969nRuMPKtE5TKKAVhs8HkfMqnn0SRYPMmdVjQc=
      volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./plugins:/opt/airflow/plugins
      entrypoint: >
        bash -c "
        airflow db upgrade &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        airflow scheduler
        "
      depends_on:
        - postgres